Add WebAuthn Example
stytchauth/stytch-nextjs-integration pull request #48
Opened 2021-12-07 21:52 UTC by kaden-stytch

2021-12-07 21:55 UTC, mary-stytch commented
@kaden-stytch can you please update the screenshot in the README?

2021-12-07 21:56 UTC, mary-stytch commented
> @kaden-stytch can you please update the screenshot in the README?

nvm, I see we'll need to update the image in our public CDN instead.

2021-12-07 22:18 UTC, alex-stytch approved these changes
LGTM – Approving from a WebAuthn API prospective

2021-12-08 21:29 UTC, chris-stytch commented on README.md
> +Next we'll configure the appropriate redirect URLs for your project, you'll set these magic link URLs for your project in the [Redirect URLs](https://stytch.com/dashboard/redirect-urls) section of yo
Not a blocker if you strongly prefer the wording here.

```suggestion
Next we'll configure the appropriate redirect URLs for your project, you'll set these magic link URLs for your project in the [Redirect URLs](https://stytch.com/dashboard/redirect-urls) section of your Dashboard. Add `http://localhost:3000/api/authenticate_magic_link` as both a login and sign-up redirect URL. If you'd like to try our [WebAuthn](https://stytch.com/docs/api/webauthn-overview) example integration, add `http://localhost:3000/api/authenticate_magic_link_with_webauthn` as a login and sign-up redirect URL as well.
```

I'm still mulling over how we want to do this long term as the complexity grows here, right now I'm leaning towards some sort of side bar instructions within the example app itself, but for now I think I want to target SDK EML and API SMS as the "default" integrations here, and the rest as "try these as well".

2021-12-08 21:32 UTC, chris-stytch requested changes
Works great locally and with `vercel dev`, but running into a timeout issue when sending the EML on Vercel, see https://stytch-nextjs-integration-291tr1ikm-stytch-auth.vercel.app/

The problem isn't obvious to me. @kaden-stytch let me know if you see something obvious that I missed. Going to move on to https://github.com/stytchauth/stytch-nextjs-integration/pull/47 so we can get that into this PR and circle back.

2021-12-08 22:05 UTC, chris-stytch approved these changes

2021-12-08 23:27 UTC, merged